{
 "title": "General view",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TH1 temp panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  temp\nFROM therm\nWHERE\n  $__timeFilter(datetime) AND id = 'TH1'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  target\nFROM therm\nwhere $__timeFilter(datetime) and id = 'TH1'"
    }
   ]
  },
  {
   "title": "TH1 Target",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  temp,\n  id,\n  target\nFROM therm\nWHERE\n  $__timeFilter(datetime) and id = 'TH1'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "TH2 temp panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  temp\nFROM therm\nWHERE\n  $__timeFilter(datetime) AND id = 'TH2'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  target\nFROM therm\nwhere $__timeFilter(datetime) and id = 'TH2'\n\n"
    }
   ]
  },
  {
   "title": "TH2 Target",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  temp,\n  id,\n  target\nFROM therm\nWHERE\n  $__timeFilter(datetime) and id = 'TH2'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "TH3 temp panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  temp\nFROM therm\nWHERE\n  $__timeFilter(datetime) AND id = 'TH3'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  target\nFROM therm\nwhere $__timeFilter(datetime) and id = 'TH3'"
    }
   ]
  },
  {
   "title": "TH3 Target",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  temp,\n  id,\n  target\nFROM therm\nWHERE\n  $__timeFilter(datetime) and id = 'TH3'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Therm Tabel panel",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  datetime AS \"time\",\r\n  temp,\r\n  state,\r\n  id,\r\n  target\r\nFROM therm\r\nORDER BY datetime desc"
    }
   ]
  }
 ]
}