{
 "title": "TH2",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  temp\nFROM therm\nWHERE\n  $__timeFilter(datetime) AND id = 'TH2'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  target\nFROM therm\nWHERE\n  $__timeFilter(datetime) AND id = 'TH2'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DB table",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  datetime AS \"time\",\r\n  temp,\r\n  state,\r\n  target\r\nFROM therm\r\nWHERE id = 'TH2'\r\nORDER BY datetime desc"
    }
   ]
  },
  {
   "title": "MAX & MIN Temp",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(temp), MIN(temp)\nFROM therm\nWHERE id = 'TH2'\nORDER BY 1"
    }
   ]
  }
 ]
}