apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: $GRAFANA_DATA_HOST
    database: test
    user: postgres
    editable: true
    idDefault: true
    secureJsonData:
      password: password
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1200
      timescaledb: true